//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuraevKursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int IDPrice { get; set; }
        public int IDProduct { get; set; }
        public int Price1 { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual WareHouse WareHouse { get; set; }
    }
}
